#生产
server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mulit_blog_datasource?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
logging:
  file:
    path: E:\workspace\myselfworkspace\blog-project